apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: core-db
  template:
    metadata:
      labels:
        app: ods
        service: core-db
    spec:
      containers:
        - name: core-db
          image: postgres
          imagePullPolicy: Always
        

          env:
            - name: POSTGRES_USER
              value: "coreservice"
            - name: POSTGRES_PASSWORD
              value: "admin"

          ports:
            - containerPort: 5432 

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10