apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: core
  template:
    metadata:
      labels:
        app: ods
        service: core
    spec:
      containers:
        - name: core-service
          image: docker.pkg.github.com/jvalue/open-data-service/core:latest
          imagePullPolicy: Always
      
          env:
            - name: DB_URL 
              value: "jdbc:postgresql://core-db-service/coreservice"

          ports:
            - containerPort: 8080

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10