apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: ui
  template:
    metadata:
      labels:
        app: ods
        service: ui
    spec:
      containers:
        - name: ui-service

          env:
            - name: UI_BASE_URL
              value: "http://ods.cs.fau.de"
            - name: CORE_SERVICE_URL
              value: "http://ods.cs.fau.de/api/core"
            - name: STORAGE_SERVICE_URL
              value: "http://ods.cs.fau.de/api/storage"
            - name: TRANSFORMATION_SERVICE_URL
              value: "http://ods.cs.fau.de/api/transformation"