name: Open Data Service (ODS)

on: [push, pull_request, workflow_dispatch]

jobs:

  # ----------------- ADAPTER SERVICE --------------------

  adapter-build:
    name: Adapter Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build adapter

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.it.yml build adapter-it
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d adapter
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up --exit-code-from adapter-it adapter-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.it.yml down

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/adapter
          docker save $IMAGE_ID > adapter.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: adapter-artifact
          path: adapter.tar

  # ----------------- SCHEDULER SERVICE --------------------

  scheduler-build:
    name: Scheduler Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build scheduler

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.it.yml build scheduler-it
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d scheduler
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up --exit-code-from scheduler-it scheduler-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.it.yml down

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/scheduler
          docker save $IMAGE_ID > scheduler.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: scheduler-artifact
          path: scheduler.tar


  # ----------------- STORAGE SERVICE --------------------

  storage-build:
    name: Storage Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build storage
          docker-compose -f docker-compose.yml build storage-db-liquibase
          docker-compose -f docker-compose.yml build storage-mq

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.it.yml build storage-it
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d storage-db
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up storage-db-liquibase
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d storage-mq
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d storage
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up --exit-code-from storage-it storage-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.it.yml down

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID_STORAGE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage
          IMAGE_ID_LIQUIBASE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage-db-liquibase
          IMAGE_ID_STORAGEMQ=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage-mq

          docker save $IMAGE_ID_STORAGE > storage_postgrest.tar
          docker save $IMAGE_ID_LIQUIBASE > storage_liquibase.tar
          docker save $IMAGE_ID_STORAGEMQ > storage_mq.tar

      - name: Upload Storage Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: storage-artifact
          path: storage_postgrest.tar

      - name: Upload Liquibase Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: liquibase-artifact
          path: storage_liquibase.tar

      - name: Upload Storage-MQ Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: storagemq-artifact
          path: storage_mq.tar


  # ----------------- TRANSFORMATION SERVICE --------------------

  transformation-build:
    name: Transformation Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build transformation

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.it.yml build transformation-it
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d transformation
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up --exit-code-from transformation-it transformation-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.it.yml down

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/transformation
          docker save $IMAGE_ID > transformation.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: transformation-artifact
          path: transformation.tar


  # ----------------- NOTIFICATION SERVICE --------------------

  notification-build:
    name: Notification Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build notification

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.it.yml build notification-it
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up -d notification
          docker-compose -f docker-compose.yml -f docker-compose.it.yml up --exit-code-from notification-it notification-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.it.yml down

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/notification
          docker save $IMAGE_ID > notification.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: notification-artifact
          path: notification.tar


  # ----------------- UI SERVICE --------------------

  ui-build:
    name: UI Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build ui

      - name: Save Docker image as artifact
        run: |
          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/ui
          docker save $IMAGE_ID > ui.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ui-artifact
          path: ui.tar

  # ----------------- SYSTEMTEST --------------------

  systemtest:
    name: Systemtest
    runs-on: ubuntu-latest

    needs: [adapter-build, notification-build, scheduler-build, storage-build, transformation-build, ui-build]

    steps:
      - uses: actions/checkout@v2

      - name: Download adapter artifact
        uses: actions/download-artifact@v1
        with:
          name: adapter-artifact
      - name: Download scheduler artifact
        uses: actions/download-artifact@v1
        with:
          name: scheduler-artifact
      - name: Download storage artifact
        uses: actions/download-artifact@v1
        with:
          name: storage-artifact
      - name: Download liquibase artifact
        uses: actions/download-artifact@v1
        with:
          name: liquibase-artifact
      - name: Download storagemq artifact
        uses: actions/download-artifact@v1
        with:
          name: storagemq-artifact
      - name: Download transformation artifact
        uses: actions/download-artifact@v1
        with:
          name: transformation-artifact
      - name: Download notification artifact
        uses: actions/download-artifact@v1
        with:
          name: notification-artifact

      - name: Run Systemtest
        run: |
          docker load -i ./scheduler-artifact/scheduler.tar &
          docker load -i ./storage-artifact/storage_postgrest.tar &
          docker load -i ./liquibase-artifact/storage_liquibase.tar &
          docker load -i ./storagemq-artifact/storage_mq.tar &
          docker load -i ./transformation-artifact/transformation.tar &
          docker load -i ./notification-artifact/notification.tar &
          docker load -i ./adapter-artifact/adapter.tar
          docker-compose -f docker-compose.yml -f docker-compose.st.yml up --exit-code-from system-test adapter transformation storage storage-mq notification scheduler system-test
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.st.yml down

  # ----------------- Registry Upload --------------------

  adapter_upload:
    name: Adapter Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download adapter artifact
        uses: actions/download-artifact@v1
        with:
          name: adapter-artifact


      - name: Load Docker Image from artifact
        run: |
          docker load -i ./adapter-artifact/adapter.tar

      - name: Adapter Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/adapter

          ADAPTER_VERSION=$(grep "version =" ./adapter/src/main/resources/application.properties | awk '{print $3}' | sed "s/[']//g")

          docker tag $IMAGE_ID $IMAGE_ID:$ADAPTER_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$ADAPTER_VERSION
          docker push $IMAGE_ID:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID:$ADAPTER_VERSION
          docker push $IMAGE_ID:latest


  scheduler_upload:
    name: Scheduler Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download scheduler artifact
        uses: actions/download-artifact@v1
        with:
          name: scheduler-artifact

      - name: Load Docker Image from artifact
        run: |
          docker load -i ./scheduler-artifact/scheduler.tar

      - name: Scheduler Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/scheduler

          SCHEDULER_VERSION=$(grep "version" scheduler/package.json | awk '{print $2}' | sed 's/[,"]//g')

          docker tag $IMAGE_ID $IMAGE_ID:$SCHEDULER_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$SCHEDULER_VERSION
          docker push $IMAGE_ID:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID:$SCHEDULER_VERSION
          docker push $IMAGE_ID:latest

  storage_upload:
    name: Storage Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download storage artifact
        uses: actions/download-artifact@v1
        with:
          name: storage-artifact
      - name: Download liquibase artifact
        uses: actions/download-artifact@v1
        with:
          name: liquibase-artifact

      - name: Load Docker Images from artifacts
        run: |

          docker load -i ./storage-artifact/storage_postgrest.tar
          docker load -i ./liquibase-artifact/storage_liquibase.tar

      - name: Storage Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          STORAGE_VERSION=$(grep "VERSION" ./storage/version.txt | awk '{print $3}' | sed 's/[,"]//g')

          IMAGE_ID_STORAGE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage
          IMAGE_ID_LIQUIBASE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage-db-liquibase

          docker tag $IMAGE_ID_STORAGE $IMAGE_ID_STORAGE:$STORAGE_VERSION
          docker tag $IMAGE_ID_STORAGE $IMAGE_ID_STORAGE:latest

          docker tag $IMAGE_ID_LIQUIBASE $IMAGE_ID_LIQUIBASE:$STORAGE_VERSION
          docker tag $IMAGE_ID_LIQUIBASE $IMAGE_ID_LIQUIBASE:latest

          docker push $IMAGE_ID_STORAGE:$STORAGE_VERSION
          docker push $IMAGE_ID_STORAGE:latest

          docker push $IMAGE_ID_LIQUIBASE:$STORAGE_VERSION
          docker push $IMAGE_ID_LIQUIBASE:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID_STORAGE:$STORAGE_VERSION
          docker push $IMAGE_ID_STORAGE:latest

          docker push $IMAGE_ID_LIQUIBASE:$STORAGE_VERSION
          docker push $IMAGE_ID_LIQUIBASE:latest

  transformation_upload:
    name: Transformation Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download transformation artifact
        uses: actions/download-artifact@v1
        with:
          name: transformation-artifact

      - name: Load Docker Image from artifact
        run: |
          docker load -i ./transformation-artifact/transformation.tar

      - name: Transformation Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/transformation

          TRANSFORMATION_VERSION=$(grep "version" ./transformation/package.json | awk '{print $2}' | sed 's/[,"]//g')

          docker tag $IMAGE_ID $IMAGE_ID:$TRANSFORMATION_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$TRANSFORMATION_VERSION
          docker push $IMAGE_ID:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID:$TRANSFORMATION_VERSION
          docker push $IMAGE_ID:latest

  notification_upload:
    name: Notifcation Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download notifcation artifact
        uses: actions/download-artifact@v1
        with:
          name: notification-artifact

      - name: Load Docker Image from artifact
        run: |
          docker load -i ./notification-artifact/notification.tar

      - name: Notifcation Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/notification

          NOTIFICATION_VERSION=$(grep "version" ./notification/package.json | awk '{print $2}' | sed 's/[,"]//g')

          docker tag $IMAGE_ID $IMAGE_ID:$NOTIFICATION_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$NOTIFICATION_VERSION
          docker push $IMAGE_ID:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID:$NOTIFICATION_VERSION
          docker push $IMAGE_ID:latest

  ui_upload:
    name: UI Publish
    runs-on: ubuntu-latest

    needs: [systemtest]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - name: Download ui artifact
        uses: actions/download-artifact@v1
        with:
          name: ui-artifact

      - name: Load Docker Image from artifact
        run: |
          docker load -i ./ui-artifact/ui.tar

      - name: UI Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/ui

          UI_VERSION=$(grep "version" ./ui/package.json | awk '{print $2}' | sed 's/[,"]//g')

          docker tag $IMAGE_ID $IMAGE_ID:$UI_VERSION
          docker tag $IMAGE_ID $IMAGE_ID:latest

          docker push $IMAGE_ID:$UI_VERSION
          docker push $IMAGE_ID:latest

          echo "${{ secrets.DOCKERHUB_PW }}" | docker login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push $IMAGE_ID:$UI_VERSION
          docker push $IMAGE_ID:latest

  deploy:
    name: Deploy ODS to k8s
    runs-on: ubuntu-latest

    needs: [adapter_upload, scheduler_upload, storage_upload, transformation_upload, notification_upload, ui_upload]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kubernetes'
    steps:
      - uses: actions/checkout@v2

      - run: |
          ./deployment/mk-kubeconfig.sh

      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ./deployment/kube.config

      - uses: azure/k8s-bake@v1
        with:
          renderEngine: 'kustomize'
          kustomizationPath: './deployment/kustomize/'
          kubectl-version: 'latest'
        id: bake

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: 'staging'
